### ISSUE TITLE
New visual glitches

### ISSUE THREAD

**Issue by linuz90** [linuz90/better-roam-research#11]
![image](https://user-images.githubusercontent.com/9629188/87248485-f6cd3b00-c459-11ea-9758-4ff55b1c8fe8.png)

**Comment by benwf** [comment]
Maybe this takes off some work for you — quick fix for me was:

```css
.roam-body .roam-app .roam-sidebar-container .roam-sidebar-content .starred-pages-wrapper .shortcut {
  visibility: hidden;
}
.roam-body .roam-app .roam-sidebar-container .roam-sidebar-content .top-row:hover {
  background-color: inherit;
}
.roam-body .roam-app .roam-sidebar-container .roam-sidebar-content .top-row {
  padding: 7px 20px;
}
```

**Comment by levity** [comment]
and a quick fix for the alignment of the "shortcuts" label:

```css
.roam-body .roam-app .roam-sidebar-container .roam-sidebar-content .shortcut {
  padding: 14px 24px 0;
}
```

**Comment by levity** [comment]
and a quick fix for the alignment of the "shortcuts" label:

```css
.roam-body .roam-app .roam-sidebar-container .roam-sidebar-content .shortcut {
  padding: 14px 24px 0;
}
```
