### ISSUE TITLE
Text not readable in expanded links / sidebar view

### ISSUE THREAD

**Issue by boolbaall** [linuz90/better-roam-research#13]
When a mention in the references or sidebar is expended for context, the selected paragraph color scheme (yellow highlight, white font) makes readability very tough

**Before expansion**
<img width="785" alt="Screen Shot 2020-08-10 at 15 18 48" src="https://user-images.githubusercontent.com/46777772/89792698-d4901100-db1c-11ea-9906-6cb94460356a.png">

**After expansion**
![Screen Shot 2020-08-10 at 14 24 10](https://user-images.githubusercontent.com/46777772/89792471-7fec9600-db1c-11ea-8221-5e58cad44985.png)

**Comment by jguo-uw** [comment]
A quick fix: You can change the color manually in your roam/css:

`.block-highlight-yellow {
    background-color: "color you like";
}`

**Comment by jjthrash** [comment]
To match the `.roam-highlight` styling you can use color `hsl(51,50%,18%)`

**Comment by boolbaall** [comment]
> A quick fix: You can change the color manually in your roam/css:
> 
> `.block-highlight-yellow { background-color: "color you like"; }`

Thanks for the heads up. Problem I'm having is how to actually change it while leaving the rest of the theme to apply - anytime i add a new CSS block to my roam/css, it seems to effectively switch back to the default theme, rather then be additive ...

**Comment by jjthrash** [comment]
@boolbaall Putting it in the same ` ``` ` block with the `@import` appears to work: https://www.dropbox.com/s/afmhxvycd62qccw/Screen%20Shot%202020-08-17%20at%207.25.59%20AM.png?dl=0

I.e.
```css
@import url("https://linuz90.github.io/better-roam-research/main.css");
.block-highlight-yellow { background-color: hsl(51, 50%, 18%); }
```

**Comment by jjthrash** [comment]
Even better: keep accommodating light mode:

```css
@import url("https://linuz90.github.io/better-roam-research/main.css");

@media (prefers-color-scheme: dark) {
  .block-highlight-yellow { background-color: hsl(51, 50%, 18%); }
}
```
