### ISSUE TITLE
Code blocks in dark mode are white

### ISSUE THREAD

**Issue by jenningsb2** [linuz90/better-roam-research#27]
When using the code block feature in dark mode, the output appears with a white background which can feel a bit blinding and out of place in comparison to the rest of the themes aesthetic. 
![9C3BB6C1-C173-4A17-8EC2-7F5EA931FB0F](https://user-images.githubusercontent.com/29644050/97433704-4e51c280-18f4-11eb-8c27-af4d9d533f03.jpeg)

**Comment by sooheon** [comment]
The universal search dropdown is white as well.

**Comment by iamjli** [comment]
This is an issue for me as well. Rather than change syntax highlighting, perhaps the codeblock background could be modified instead? (white codeblocks are rather jarring in dark mode anyways). 

Is there a simple way to change the white background to something less harsh and more distinctive, like a dark gray or something?

**Comment by lain3d** [comment]
@iamjli I don't have time to mess with the colors but this is what I have now.

```css
/* overall code block bg */
.rm-code-block {
   background-color: #1f2022;
}

.cm-lineNumbers {
   background-color: #1f2022;
}

/* sidebar column */
.cm-gutter {
   background-color: #1f2022;
}

/* highlight active line */
.cm-focused .cm-activeLine {
   background-color: #1f2022 !important;
}

/* highlighting */
.cm-selectionBackground {
   background: #AEB8CC !important;
}

/* wont work */
.cm-activeLineGutter {
   background-color: #1f2022 !important;
}

.cm-cursor {
   border-left: 1.2px solid #fee2e2 !important;
}

/* keyword colors */
.ͼa {
    color: #708;
}

.ͼb {
    color: #fecaca !important;
}

.ͼc {
    color: #164;
}
/**/
```
