### ISSUE TITLE
Missing dark theme styling

### ISSUE THREAD

**Issue by bryanhpchiang** [linuz90/better-roam-research#37]
Missing dark theme styling for:
- Path-based block search (Ctrl-Shift-9)
- "Find or Create Page" results (top right)

Not sure if this is intentional?

**Comment by linuz90** [comment]
Didn't know about the Path-based block search. I'd leave both white as I try to not mess with some UI parts that can be a bit unpredictable. Hope it's not an issue.

**Comment by bryanhpchiang** [comment]
What do you mean by unpredictable? 

Path-based search is definitely new. I don't think the results list for "Find or Create Page" has changed at all since I started using it.

**Comment by linuz90** [comment]
You're right, I'm reopening this and I'll give it a shot when I have some time.

**Comment by watou** [comment]
Also missing dark theme styling for the new Collapsible Parentheticals feature in both collapsed 𐃏 and ((non-collapsed)) forms.

**Comment by keikhcheung** [comment]
@bryanhpchiang @watou A temporary solution is to make an extra code block under your roam/css and include all elements’ CSS classes that @linuz90’s dark theme is not supporting yet and to use `hue-rotate`.

```css
.rm-search-path-results, .bp3-transition-container, .rm-paren {
  filter: invert() hue-rotate(180deg) !important;
}

.rm-paren {
  color: hsl(0, 0%, 36%) !important;
}
```
