### ISSUE TITLE
.rm-alias is missing --accent-color in light.css

### ISSUE THREAD

**Issue by minimaldesign** [linuz90/better-roam-research#50]
Tittle is pretty self explanatory, but I had to add this to my `roam/css`:

```css
.rm-alias {
  color: var(--accent-color);
}
```

I'm using `https://linuz90.github.io/better-roam-research/light.css`. Not sure if this is true in the other versions.

Thanks for the beautiful theme!
