### ISSUE TITLE
margin-top for version-bullet

### ISSUE THREAD

**Issue by alanzchen** [linuz90/better-roam-research#51]
<img width="178" alt="Screen Shot 2021-02-14 at 12 04 36 PM" src="https://user-images.githubusercontent.com/2144783/107884972-488ce680-6ebd-11eb-9717-9267c169ff32.png">

Suggested fix:

```css
.version-bullet {
  margin-top: 8px !important;
}
```
