### ISSUE TITLE
Roam42 SmartBlock PopUp in Dark Mode is Hard to See

### ISSUE THREAD

**Issue by shawnduggan** [linuz90/better-roam-research#55]
If you install Roam42, when inserting a SmartBlock the popup menu is very hard to see in Dark Mode.

**Comment by tschoffelen** [comment]
I noticed the same, so added this little bit of custom CSS to resolve that:

```css
.tribute-container {
   box-shadow: 0 0 4px rgba(0,0,0,0.4);
}

.tribute-container ul {
    margin: 0;
    background: #121212;
    border-radius: 2px;
    overflow: hidden;
}
.tribute-container li {
  padding: 6px 12px;
  cursor: pointer;
}
.tribute-container li.highlight {
  background: #000;
}
```
